Sprint 1
stuev-is/middle.messenger.praktikum.yandex pull request #1
Opened 2021-10-09 23:17 UTC by ArminaAiren

2021-10-11 14:57 UTC, bhoodream requested changes
Лаконичная работа, но требуются некоторые доработки:
- [x] нужен .gitignore , папки: `dist`, `.cache` и `node_modules` определенно нужно игнорировать
- [ ] перекрестные сслыки с формы входа/регистрации ведут на некорректный адрес:  https://goofy-mahavira-d20d55.netlify.app/src/pages/login/src/pages/registration/reg.html
- [x] одним из требований первого спринта являются макеты, я к сожалению не нашел сслыки на фигму или изображения в проекте
- [ ] нет команды `start` для запуска проекта. Дев режим (npm run dev), для продакшена нужна отдельная команда, обычно это команда `start`, которая включает сборку проекта и запуск приложения
- [x] нужно перепроверить использование `postcss`, потому что сейчас создается впечатление, что он ничего не делает и не используется сборщиком...

2021-10-11 14:57 UTC, bhoodream commented on postcss.config.js
> +    //   require('postcss-mixins'),
Было бы хорошо не засорять проект комментариями. Если комментарий все же нужен, лучше оставлять пояснения почему он нужен.

2021-10-11 14:57 UTC, bhoodream commented on server.js
> +const PORT = 3000;
Такие переменные как `PORT`, которые являются особенностями окружения, принято брать из переменных окружения, `process.env.PORT` например. Переменные окружения являются удобным способом конфигурирования приложения не меняя код.

2021-10-11 14:57 UTC, bhoodream commented on src/modules/button/button.tmpl.js
> +module.exports = `<input class="button" type="submit" value={{text}}>`;
Для кнопки более семантически подходящим компонентом является `button`.
Тип для элемента `button` лучше тоже прописывать, чтобы браузер не гадал, какую роль играет в данном контексте этот элемент. В основном для кнопок используется тип, опять же, `button`, но может быть и `submit/reset`.

2021-10-11 15:32 UTC, stuev-is commented
> * [ ]  одним из требований первого спринта являются макеты, я к сожалению не нашел сслыки на фигму или изображения в проекте

я так понял из задания, что макеты не обязательно делать самому, а можно взять за основу готовые из проекта. но ссылку на готовые могу добавить в ридми)

2021-10-11 15:44 UTC, stuev-is commented
> * [ ]  нет команды `start` для запуска проекта. Дев режим (npm run dev), для продакшена нужна отдельная команда, обычно это команда `start`, которая включает сборку проекта и запуск приложения

![image](https://user-images.githubusercontent.com/91697565/136818625-48d2e8de-3b26-4c1e-9741-28d639ee4269.png)
да вроде есть, или я не понимаю чего от меня хотят

2021-10-11 15:46 UTC, stuev-is commented
> * [ ]  нужно перепроверить использование `postcss`, потому что сейчас создается впечатление, что он ничего не делает и не используется сборщиком...


не знаю, откуда у вас такое впечатление, он используется. простой тест: если убрать строчку с postcss-nested, то стили разваливаются. потому что, собственно, нестинг оттуда используется

2021-10-12 11:36 UTC, bhoodream approved these changes
Все круто! Апрув :)

- [ ] .cache, которая появляется после билда тоже бы заигнорить
- [ ] насчет `postcss`, впечатление сложилось из за того, что он не выдает ошибку, если подключить несуществующий пакет, а проверял я на `autoprefixer`, который твои стили никак не модифицирует (ну по крайней мере я не заметил, мельком глянув). Так что да, приношу извинения, за свои неверные впечатления :)
- [ ] насчет макетов, я руководствовался этим текстом из заданий 1-ого спринта (в котором на самом деле остается открытым вопрос, нужно ли вообще что-то добавлять): Если рисовали на листе бумаги, сохраните JPG или PNG фотографии прототипов в папку ui в корне репозитория. Если сделали прототип в Figma, добавьте ссылку в README.md.
- [ ] насчет `npm start`, не знаю как так вышло, но за внушительный промежуток времени, в течение которого я занимаюсь фронтенд разработкой, я так ни разу и не наткнулся на дефолтное поведение `npm` при отсутствующем `start` скрипте. Круто! :)

2021-10-15 07:31 UTC, merged