Sprint 2
stuev-is/middle.messenger.praktikum.yandex pull request #2
Opened 2021-10-28 10:12 UTC by stuev-is

2021-10-28 21:20 UTC, bhoodream requested changes
Все круто! Код лаконичный, приятно читать и разбираться. Но есть несколько нюансов, которые хотелось бы доработать:
- [x] хотелось бы видеть какая именно ошибка мешает мне при заполнении формы (например, "допустимы только те то символы..."), сейчас же инпут просто подсвечивается красным и не дает никакого фидбэка, что не идет на пользу UX...
- [x] нужно устранить проблемы с рендером атрибутов в элементах, связанные с отсутствием двойных кавычек, например `value={{ value }}`
- [x] `./server.js` раздает исходники, необходимо сделать, чтобы раздавал `dist`
- [x] в консоли присутствует неприятная ошибка `Uncaught ReferenceError: parcelRequire is not defined`, на любой странице, хотелось бы понять ее причину и избавиться от нее

Удачи!

2021-10-28 21:20 UTC, bhoodream commented on src/components/input/input.tmpl.ts
> +const tmpl =  `<input class="input input_error-{{error}}" id={{name}} type={{type}} name={{name}} value={{ value }} maxlength={{maxlength}}>`;
Так как `id` на странице должен быть уникальным, использовать его лучше аккуратно. Определение `id` инпута с помощью `name` атрибута, может привести к тому, что на странице окажется два и более элемента с одинаковым `id`, что нарушит его уникальность и приведет к невалидному html, а также может стать причиной некорректной работы селекторов и вообще браузера.

Произойти такое может в любой момент, так как иногда требуется добавить несколько одинаковых форм (например авторизации) на страницу. Сейчас на форме регистрации можно увидеть такие предупреждения в консоли браузера (Google Chrome): `[DOM] Found 2 elements with non-unique id #password: (More info: https://goo.gl/9p2vKq)`

Я бы рекомендовал использовать `id` только на уникальных для страницы элементах. Для тех элементов, которые гарантировано могут встретиться на странице только один раз, как например, контейнер для рендера приложения, типа `<div id="app" />`.

2021-10-28 21:20 UTC, bhoodream commented on src/components/label/label.tmpl.ts
> +const tmpl =  `<label for={{name}} class="label">{{label}}</label>`;
`label` элемент все таки линкуется к инпуту через `id` атрибут, а не через `name`. Поэтому использовать `name` параметр здесь мне кажется не совсем корректно.

Часто для того чтобы слинковать лэйбл с инпутом используют вложенность, то есть такая структура элементов `<lable><input ... /></label>` будет автоматически присваивать лэйбл к инпуту, без дополнительных атрибутов `for` и `id`.

2021-10-28 21:20 UTC, bhoodream commented on src/lib/block.ts
> +      eventBus.on(Block.EVENTS.INIT, this.init.bind(this));
Определение метода класса через стрелочные функции, позволяет обходиться без биндов при использовании этих методов как колбэков. Достигается это тем, что изменить контекст стрелочной функции невозможно, так как она не имеет своего контекста, а использует тот, который имеется при ее определении.

Например:
```
init = () => {
  this._createResources();
  this.eventBus().emit(Block.EVENTS.FLOW_CDM);
}
```

2021-10-28 21:20 UTC, bhoodream commented on src/lib/fetch.ts
> +        return this.request(urlWithParams, {...options, method: METHODS.GET}, options.timeout);
Интересно, что ты достаешь `timeout` из опшенов и прокидываешь их 3 аргументом, когда по идее его можно было таким же образом взять прямо из опшенов внутри `this.request`.

2021-10-28 21:20 UTC, bhoodream commented on src/lib/fieldsValidation/fieldsValidation.test.ts
> +TEST_CASES_LOGIN.forEach(test => {
Не помешало бы все эти `it` завернуть в какой-то объединяющий их `describe`, для красоты и порядка :)

2021-10-28 21:20 UTC, bhoodream commented on src/pages/chats/chats.css
> +        color: #fff;
Белый цвет тоже в любой момент может потребоваться заменить. По идее его тоже уместно хранить в переменной.

Также насчет именования переменных, лучше придерживаться семантического именования цветов, что-то типа `primary`, `secondary`, `accent` и тп, вместо `color-blue`, `color-gray` и тп.

2021-10-28 21:20 UTC, bhoodream commented on src/pages/chats/chats.css
> +        overflow-y: scroll;
Постоянно видимый неактивный скролл возможно так себе идея, наверное тут уместнее было бы использовать `auto` значение.

Также, так как у `chats__message-container` нет фиксированной высоты, у элемента `chats__messages` никогда не произойдет переполнение.

2021-10-28 21:20 UTC, bhoodream commented on src/pages/chats/chats.tmpl.ts
> +// chats = [ chat ]
Закомментированный код рекомендуется убирать из проекта, чтобы он не засорял кодовую базу. Если ты это оставил себе в виде напоминания какие данные здесь используются, мне кажется лучше оформить их как полноценные типы/интерфейсы тайпскрипта

2021-10-28 21:20 UTC, bhoodream commented on src/pages/chats/chats.ts
> +const chatsListCompiled = chatsList(chats);
Выглядит, что переменные `chatsListCompiled`, `messagesCompiled` и `chatFormCompiled` излишни. По идее от них можно избавиться и результат компилирования использовать сразу первым аргументом функции `insertBlock`

2021-10-28 21:20 UTC, bhoodream commented on src/pages/registration/reg.ts
> +    password2: 'assword-input-2',
мелкая опечатка `assword-input-2` :)

2021-10-28 21:20 UTC, bhoodream commented on src/components/input/input.tmpl.ts
> +const tmpl =  `<input class="input input_error-{{error}}" id={{name}} type={{type}} name={{name}} value={{ value }} maxlength={{maxlength}}>`;
Еще один момент, сразу показалось, что как то странно выглядит элемент, и бросилось в глаза отсутствие кавычек, например `value={{ value }}`. И да, это все же приводит к проблемам, было бы хорошо добавить двойные кавычки, типа так `value="{{ value }}"`. 

Проблема выглядит так:

https://user-images.githubusercontent.com/1740470/139334957-7ab20b7b-1155-49ab-8e35-41a7cff8ab1d.mov

2021-10-29 05:44 UTC, stuev-is commented on src/pages/registration/reg.ts
> +    password2: 'assword-input-2',
зато какая красивая))

2021-10-29 05:59 UTC, stuev-is commented on src/pages/chats/chats.css
> +        color: #fff;
как называть -- вкусовщина, я б вообще не использовал переменные, если честно) мне понятнее по цветам)

2021-10-29 06:03 UTC, stuev-is commented on src/lib/fetch.ts
> +        return this.request(urlWithParams, {...options, method: METHODS.GET}, options.timeout);
я это нагло содрал из теории курса, но похоже что так сделано, чтоб было удобнее задать дефолтный таймаут

2021-10-29 06:06 UTC, stuev-is commented on src/lib/block.ts
> +      eventBus.on(Block.EVENTS.INIT, this.init.bind(this));
я догадывался про это) это тоже была копипаста из теории)

2021-10-29 06:45 UTC, stuev-is commented
`в консоли присутствует неприятная ошибка Uncaught ReferenceError: parcelRequire is not defined, на любой странице, хотелось бы понять ее причину и избавиться от нее`

она вроде довольно приятная (в том плане, что ничего не ломает), удалось нагуглить не очень изящный способ ее решения

2021-10-29 06:48 UTC, stuev-is commented
`./server.js раздает исходники, необходимо сделать, чтобы раздавал dist`

ок, но оно, кажется, в проекте сейчас делает примерно ничего)

2021-10-29 10:26 UTC, bhoodream approved these changes
Все круто! Спасибо за работу!

2021-11-09 21:25 UTC, merged